seed: 42
device: cuda
output_dir: outputs/unet_fast_gpu

data:
  root_dir: data
  train_split: train
  val_split: valid
  test_split: test
  task_mode: multiclass
  img_size: 384
  batch_size: 4
  num_workers: 2
  persistent_workers: true
  prefetch_factor: 1

model:
  encoder_name: resnet34
  encoder_weights: imagenet
  in_channels: 3

train:
  epochs: 30
  learning_rate: 0.0003
  weight_decay: 0.00001
  amp: true
  threshold: 0.5
  cudnn_benchmark: true
  channels_last: true
  compile: true
  compile_mode: reduce-overhead
  grad_accum_steps: 1
  early_stopping_patience: 6
  monitor_metric: val_dice
